{
 "title": "PHP Applications",
 "description": "Metrics of all PHP Applications",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(basic_info, job)" } },
   {
    "name": "name",
    "label": "Name",
    "query": {
     "query": "label_values(basic_info{job=~\"$job\"}, nodename)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(basic_info{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "port",
    "label": "Port",
    "query": {
     "query": "label_values(basic_info{instance=~\"$node:(.*)\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "basic_info{instance=\"$node:$port\"}"
    }
   ]
  },
  {
   "title": "Application Domain",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "basic_info{instance=\"$node:$port\"}"
    }
   ]
  },
  {
   "title": "Application Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "basic_info{instance=\"$node:$port\"}"
    }
   ]
  },
  {
   "title": "Enviroment",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "basic_info{instance=\"$node:$port\"}"
    }
   ]
  },
  {
   "title": "Amount of Git commits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "basic_commits{instance=\"$node:$port\"}"
    }
   ]
  },
  {
   "title": "Amount of Pages",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "basic_pages{instance=\"$node:$port\"}"
    }
   ]
  },
  {
   "title": "Application Sizes in MB",
   "type": "timeseries",
   "description": "We have three types:  \ngit = size of all git Data (Folder .git)  \nplain = size of Applicaion without git data  \ntotal = size of Application with git data (real size)  ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "basic_appsize{instance=\"$node:$port\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "description": "Metric Time in Seconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "basic_mtime{instance=\"$node:$port\"}"
    }
   ]
  },
  {
   "title": "ToDo's",
   "type": "stat",
   "description": "Amount of ToDo Notifications in the Code.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "basic_todos{instance=\"$node:$port\"}"
    }
   ]
  }
 ]
}